from sqlalchemy import Column, String, Integer, ARRAY
from sqlalchemy.dialects.postgresql import HSTORE
from sqlalchemy.ext.mutable import MutableDict
from sqlalchemy.ext.declarative import declarative_base
import seedparser

base = declarative_base()

class LocationMetadata(base):
    __tablename__ = 'location-metadata'
    location = Column(String, primary_key=True)
    x = Column(Integer)
    y = Column(Integer)
    map = Column(String)
    requirements = Column(ARRAY(String))
    region = Column(String)
    count = Column(Integer)

class Playthrough(base):
    __tablename__ = 'playthroughs'
    seed_guid = Column(String, primary_key=True)
    seed_number = Column(Integer)
    playthrough = Column(String)


    def __init__(self, seed_guid : str, shops : dict):
        self.seed_guid = seed_guid
        for k,v in shops.items():
            setattr(self, k, v)


class Locations(base):
    __tablename__ = 'locations'
    seed_guid = Column(String, primary_key=True)
    SahasrahlasHutLeft = Column(String)
    SahasrahlasHutMiddle = Column(String)
    SahasrahlasHutRight = Column(String)
    Sahasrahla = Column(String)
    KingZora = Column(String)
    PotionShop = Column(String)
    ZorasLedge = Column(String)
    WaterfallFairyLeft = Column(String)
    WaterfallFairyRight = Column(String)
    MasterSwordPedestal = Column(String)
    KingsTomb = Column(String)
    KakarikoTavern = Column(String)
    ChickenHouse = Column(String)
    KakarikoWellTop = Column(String)
    KakarikoWellLeft = Column(String)
    KakarikoWellMiddle = Column(String)
    KakarikoWellRight = Column(String)
    KakarikoWellBottom = Column(String)
    BlindsHideoutTop = Column(String)
    BlindsHideoutLeft = Column(String)
    BlindsHideoutRight = Column(String)
    BlindsHideoutFarLeft = Column(String)
    BlindsHideoutFarRight = Column(String)
    PegasusRocks = Column(String)
    BottleMerchant = Column(String)
    MagicBat = Column(String)
    SickKid = Column(String)
    LostWoodsHideout = Column(String)
    LumberjackTree = Column(String)
    GraveyardLedge = Column(String)
    Mushroom = Column(String)
    FloodgateChest = Column(String)
    LinksHouse = Column(String)
    AginahsCave = Column(String)
    MiniMoldormCaveFarLeft = Column(String)
    MiniMoldormCaveLeft = Column(String)
    MiniMoldormCaveRight = Column(String)
    MiniMoldormCaveFarRight = Column(String)
    IceRodCave = Column(String)
    Hobo = Column(String)
    BombosTablet = Column(String)
    Cave45 = Column(String)
    CheckerboardCave = Column(String)
    MiniMoldormCaveNPC = Column(String)
    Library = Column(String)
    MazeRace = Column(String)
    DesertLedge = Column(String)
    LakeHyliaIsland = Column(String)
    SunkenTreasure = Column(String)
    FluteSpot = Column(String)
    Sanctuary = Column(String)
    SewersSecretRoomLeft = Column(String)
    SewersSecretRoomMiddle = Column(String)
    SewersSecretRoomRight = Column(String)
    SewersDarkCross = Column(String)
    HyruleCastleBoomerangChest = Column(String)
    HyruleCastleMapChest = Column(String)
    HyruleCastleZeldasCell = Column(String)
    LinksUncle = Column(String)
    SecretPassage = Column(String)
    EasternPalaceCompassChest = Column(String)
    EasternPalaceBigChest = Column(String)
    EasternPalaceCannonballChest = Column(String)
    EasternPalaceBigKeyChest = Column(String)
    EasternPalaceMapChest = Column(String)
    EasternPalaceBoss = Column(String)
    EasternPalacePrize = Column(String)
    DesertPalaceBigChest = Column(String)
    DesertPalaceMapChest = Column(String)
    DesertPalaceTorch = Column(String)
    DesertPalaceBigKeyChest = Column(String)
    DesertPalaceCompassChest = Column(String)
    DesertPalaceBoss = Column(String)
    DesertPalacePrize = Column(String)
    OldMan = Column(String)
    SpectacleRockCave = Column(String)
    EtherTablet = Column(String)
    SpectacleRock = Column(String)
    SpiralCave = Column(String)
    MimicCave = Column(String)
    ParadoxCaveLowerFarLeft = Column(String)
    ParadoxCaveLowerLeft = Column(String)
    ParadoxCaveLowerRight = Column(String)
    ParadoxCaveLowerFarRight = Column(String)
    ParadoxCaveLowerMiddle = Column(String)
    ParadoxCaveUpperLeft = Column(String)
    ParadoxCaveUpperRight = Column(String)
    FloatingIsland = Column(String)
    TowerofHeraBigKeyChest = Column(String)
    TowerofHeraBasementCage = Column(String)
    TowerofHeraMapChest = Column(String)
    TowerofHeraCompassChest = Column(String)
    TowerofHeraBigChest = Column(String)
    TowerofHeraBoss = Column(String)
    TowerofHeraPrize = Column(String)
    CastleTowerRoom03 = Column(String)
    CastleTowerDarkMaze = Column(String)
    SuperbunnyCaveTop = Column(String)
    SuperbunnyCaveBottom = Column(String)
    HookshotCaveTopRight = Column(String)
    HookshotCaveTopLeft = Column(String)
    HookshotCaveBottomLeft = Column(String)
    HookshotCaveBottomRight = Column(String)
    SpikeCave = Column(String)
    Catfish = Column(String)
    Pyramid = Column(String)
    PyramidFairyLeft = Column(String)
    PyramidFairyRight = Column(String)
    Brewery = Column(String)
    CShapedHouse = Column(String)
    ChestGame = Column(String)
    HammerPegs = Column(String)
    BumperCave = Column(String)
    Blacksmith = Column(String)
    PurpleChest = Column(String)
    HypeCaveTop = Column(String)
    HypeCaveMiddleRight = Column(String)
    HypeCaveMiddleLeft = Column(String)
    HypeCaveBottom = Column(String)
    Stumpy = Column(String)
    HypeCaveNPC = Column(String)
    DiggingGame = Column(String)
    MireShedLeft = Column(String)
    MireShedRight = Column(String)
    PalaceofDarknessShooterRoom = Column(String)
    PalaceofDarknessBigKeyChest = Column(String)
    PalaceofDarknessTheArenaLedge = Column(String)
    PalaceofDarknessTheArenaBridge = Column(String)
    PalaceofDarknessStalfosBasement = Column(String)
    PalaceofDarknessMapChest = Column(String)
    PalaceofDarknessBigChest = Column(String)
    PalaceofDarknessCompassChest = Column(String)
    PalaceofDarknessHarmlessHellway = Column(String)
    PalaceofDarknessDarkBasementLeft = Column(String)
    PalaceofDarknessDarkBasementRight = Column(String)
    PalaceofDarknessDarkMazeTop = Column(String)
    PalaceofDarknessDarkMazeBottom = Column(String)
    PalaceofDarknessBoss = Column(String)
    PalaceofDarknessPrize = Column(String)
    SwampPalaceEntrance = Column(String)
    SwampPalaceBigChest = Column(String)
    SwampPalaceBigKeyChest = Column(String)
    SwampPalaceMapChest = Column(String)
    SwampPalaceWestChest = Column(String)
    SwampPalaceCompassChest = Column(String)
    SwampPalaceFloodedRoomLeft = Column(String)
    SwampPalaceFloodedRoomRight = Column(String)
    SwampPalaceWaterfallRoom = Column(String)
    SwampPalaceBoss = Column(String)
    SwampPalacePrize = Column(String)
    SkullWoodsBigChest = Column(String)
    SkullWoodsBigKeyChest = Column(String)
    SkullWoodsCompassChest = Column(String)
    SkullWoodsMapChest = Column(String)
    SkullWoodsBridgeRoom = Column(String)
    SkullWoodsPotPrison = Column(String)
    SkullWoodsPinballRoom = Column(String)
    SkullWoodsBoss = Column(String)
    SkullWoodsPrize = Column(String)
    ThievesTownAttic = Column(String)
    ThievesTownBigKeyChest = Column(String)
    ThievesTownMapChest = Column(String)
    ThievesTownCompassChest = Column(String)
    ThievesTownAmbushChest = Column(String)
    ThievesTownBigChest = Column(String)
    ThievesTownBlindsCell = Column(String)
    ThievesTownBoss = Column(String)
    ThievesTownPrize = Column(String)
    IcePalaceBigKeyChest = Column(String)
    IcePalaceCompassChest = Column(String)
    IcePalaceMapChest = Column(String)
    IcePalaceSpikeRoom = Column(String)
    IcePalaceFreezorChest = Column(String)
    IcePalaceIcedTRoom = Column(String)
    IcePalaceBigChest = Column(String)
    IcePalaceBoss = Column(String)
    IcePalacePrize = Column(String)
    MiseryMireBigChest = Column(String)
    MiseryMireMainLobby = Column(String)
    MiseryMireBigKeyChest = Column(String)
    MiseryMireCompassChest = Column(String)
    MiseryMireBridgeChest = Column(String)
    MiseryMireMapChest = Column(String)
    MiseryMireSpikeChest = Column(String)
    MiseryMireBoss = Column(String)
    MiseryMirePrize = Column(String)
    TurtleRockChainChomps = Column(String)
    TurtleRockCompassChest = Column(String)
    TurtleRockRollerRoomLeft = Column(String)
    TurtleRockRollerRoomRight = Column(String)
    TurtleRockBigChest = Column(String)
    TurtleRockBigKeyChest = Column(String)
    TurtleRockCrystarollerRoom = Column(String)
    TurtleRockEyeBridgeBottomLeft = Column(String)
    TurtleRockEyeBridgeBottomRight = Column(String)
    TurtleRockEyeBridgeTopLeft = Column(String)
    TurtleRockEyeBridgeTopRight = Column(String)
    TurtleRockBoss = Column(String)
    TurtleRockPrize = Column(String)
    GanonsTowerBobsTorch = Column(String)
    GanonsTowerDMsRoomTopLeft = Column(String)
    GanonsTowerDMsRoomTopRight = Column(String)
    GanonsTowerDMsRoomBottomLeft = Column(String)
    GanonsTowerDMsRoomBottomRight = Column(String)
    GanonsTowerRandomizerRoomTopLeft = Column(String)
    GanonsTowerRandomizerRoomTopRight = Column(String)
    GanonsTowerRandomizerRoomBottomLeft = Column(String)
    GanonsTowerRandomizerRoomBottomRight = Column(String)
    GanonsTowerFiresnakeRoom = Column(String)
    GanonsTowerMapChest = Column(String)
    GanonsTowerBigChest = Column(String)
    GanonsTowerHopeRoomLeft = Column(String)
    GanonsTowerHopeRoomRight = Column(String)
    GanonsTowerBobsChest = Column(String)
    GanonsTowerTileRoom = Column(String)
    GanonsTowerCompassRoomTopLeft = Column(String)
    GanonsTowerCompassRoomTopRight = Column(String)
    GanonsTowerCompassRoomBottomLeft = Column(String)
    GanonsTowerCompassRoomBottomRight = Column(String)
    GanonsTowerBigKeyChest = Column(String)
    GanonsTowerBigKeyRoomLeft = Column(String)
    GanonsTowerBigKeyRoomRight = Column(String)
    GanonsTowerMiniHelmasaurRoomLeft = Column(String)
    GanonsTowerMiniHelmasaurRoomRight = Column(String)
    GanonsTowerPreMoldormChest = Column(String)
    GanonsTowerMoldormChest = Column(String)
    
    def __init__(self, seed_guid : str, locations : dict):
        self.seed_guid = seed_guid
        for k,v in locations.items():
            setattr(self, seedparser.getLocationMap()[k], v)

class Seeds(base):
    __tablename__ = 'seeds'
    seed_guid = Column(String, primary_key=True)
    location = Column(String, primary_key=True)
    #item = Column(String, primary_key=True)